server:
  port: 8888


#应用名称
spring:
  application:
    name: dcloud-gateway

  #服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 139.159.250.149:8848
        username: nacos
        password: nacos

